title: Jessica Schrouff's Homepage
page-top-title: Jessica Schrouff
top-section-bg-text: Responsible AI and Healthcare
home-subtitle: Jessica Schrouff&ensp;|&ensp;
copyright-text: '&copy; Jessica Schrouff 2025. All Rights Reserved.'
